In [2]:
import numpy as np
sample_list = [1,2,3]
list_array = np.array(sample_list)
print(list_array)

[1 2 3]


In [6]:
tup = (1,2,3)
my_tup_array = np.array(tup)
print(my_tup_array)

[1 2 3]


In [10]:
def multiply_loops(A, B):
    c=np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c

In [11]:
def multiply_vector(A, B):
     return A @ B

In [12]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

In [13]:
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

1.19 s ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
349 µs ± 143 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
tup_dim = (3, 4)

In [100]:
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [101]:
my_ones_array = np.ones(tup_dim, dtype=np.int16)
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [102]:
my_seven_array = np.full( tup_dim, 7, dtype=np.int16)
print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [103]:
import numpy as np
my_identity_array = np.identity(4, dtype=np.float64)
print(my_identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [128]:
my_rand_array = np.random.rand(3,4)

In [130]:
tup_dim = (3, 4)
my_uninitialized_array = np.empty(tup_dim)
print(my_uninitialized_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [141]:
my_range_array = np.arange(10, 30, 5)
print(my_range_array)

[10 15 20 25]


In [142]:
my_spaced_array = np.linspace(0, 5/3, 6)
print(my_spaced_array)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [161]:
my_array = np.array([[1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16]])


In [172]:
print(my_array.ndim)

2


In [173]:
print(my_array.shape)

(3, 4)


In [174]:
print(my_array.dtype)

int64


In [175]:
print(my_array.size)

12


In [178]:
import numpy as np
import os
import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [179]:
FILE = 'housing_short.csv'
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

In [180]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [181]:
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [190]:
import numpy as np
my_arr = np.genfromtxt('my_file.txt', skip_header=2, filling_values=9999999)

OSError: my_file.txt not found.

In [1]:
import numpy as np
import os
HOUSING_PATH = '/cxldata/datasets/project/housing'
FILE = os.path.join(HOUSING_PATH, "housing.csv")
def load_housing_dataset(file=FILE):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

result_arr = load_housing_dataset('/cxldata/datasets/project/housing/housing.csv')
print(len(result_arr))
print(result_arr)

20640
[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [2]:
import numpy as np
my_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
my_arr.resize(3, 4)
print(my_arr)

[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]]


In [6]:
my_arr = np.arange(9)
print(my_arr)
my_new_arr = my_arr.reshape(-1,3)
print(my_new_arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
my_new_arr = my_arr.reshape(3,3)
print(my_new_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
import numpy as np
my_first_arr = np.arange(1, 9)
my_new_arr = my_first_arr.reshape(2, 4)
print(my_new_arr)
print(my_first_arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [33]:
import numpy as np
my_second_arr = np.arange(9)
my_updated_arr = my_second_arr.reshape(-1, 3)
print(my_updated_arr)
print(my_second_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [43]:
import numpy as np
my_orig_arr = np.array([1, 15, 3, 9, 26, 7, 89, 12])
my_rev_arr = my_orig_arr[ : : -1]
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [44]:
my_orig_arr2 = np.array([2, 9, 17, 13, 1, 4, 20, 57])
my_orig_arr2[2 : 5] = -6
print(my_orig_arr2)

[ 2  9 -6 -6 -6  4 20 57]


In [62]:
apple = np.array([1, 8, 23, 3, 18, 91, 7, 15])
apple_slice = apple[1 : 4]
print(apple_slice)
print(apple)

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]


In [63]:
apple_slice[1] = 99999
print(apple_slice)
print(apple)

[    8 99999     3]
[    1     8 99999     3    18    91     7    15]


In [64]:
apple_slice_new = apple[2 : 5].copy()
apple_slice_new[1] = 222222
print(apple_slice_new)
print(apple)

[ 99999 222222     18]
[    1     8 99999     3    18    91     7    15]


In [79]:
from sklearn.datasets import load_sample_image
china = load_sample_image("china.jpg")
portion = china[120:250, 110:230]
print(portion)

[[[ 62  61  56]
  [ 25  22  15]
  [ 28  29  21]
  ...
  [ 21  27  23]
  [ 25  25  23]
  [ 18  13  10]]

 [[ 33  34  29]
  [ 24  24  16]
  [ 38  39  33]
  ...
  [ 21  25  24]
  [ 26  24  25]
  [ 29  23  25]]

 [[  3   3   1]
  [ 15  14  10]
  [ 29  30  25]
  ...
  [ 30  31  33]
  [ 18  16  19]
  [ 20  15  19]]

 ...

 [[ 35  32  25]
  [ 32  32  24]
  [ 28  22  22]
  ...
  [ 70  81  85]
  [ 76  88  86]
  [ 93  86  68]]

 [[ 52  51  33]
  [ 52  46  20]
  [ 50  43  25]
  ...
  [ 72  76  88]
  [ 94  99 105]
  [122 104  84]]

 [[ 58  60  39]
  [ 63  62  34]
  [ 65  67  46]
  ...
  [ 90 104 105]
  [103 119 119]
  [127 126 108]]]


In [92]:
import numpy as np
from sklearn.datasets import load_sample_image
china = load_sample_image("china.jpg")
china.reshape((427, 640, 3))
image = china[150:220, 130:250]
print(image.shape)
height, width, channels = image.shape
image_grayscale = image.mean(axis=2).astype(np.float32)
print(image_grayscale.shape)
images = image_grayscale.reshape(1, height, width, 1)
images.ndim

(70, 120, 3)
(70, 120)


4

In [95]:
import numpy as np
my_multi_arr = np.arange(20).reshape(4, 5)
my_multi_arr_portion = my_multi_arr[2:, 2:]
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [102]:
import numpy as np
my_2d_arr = np.arange(20).reshape(4, 5)
my_1d_arr = my_2d_arr.ravel()
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [110]:
import numpy as np
a_arr = np.array([60, 70, 80, 90])
b_arr = np.arange(4)
c_arr = a_arr  + b_arr
print(c_arr)

d_arr = np.array([60, 70, 80, 90])
e_arr = np.arange(4)
f_arr =  d_arr  - e_arr
print(f_arr)

[60 71 82 93]
[60 69 78 87]


In [127]:
    import numpy as np
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )
M_arr = A_arr * B_arr
print(M_arr)

[[10 72]
 [ 4 42]]


In [129]:
    C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
P_arr = np.dot(C_arr, D_arr)
print(P_arr)

[[19 94]
 [15 74]]


In [147]:
 import numpy as np
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array([ [2, 10], [4, 5] ] )
T_div = R_div / S_div
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [148]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )
T_int_div = R_int_div // S_int_div
print(T_int_div)

[[12  6]
 [ 5 23]]


In [149]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )
T_mod = R_mod % S_mod
print(T_mod)

[[0 5]
 [0 1]]


In [168]:
import numpy as np
R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )
T_exp = R_exp ** S_exp
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [177]:
import numpy as np
U = np.array([ [ 22, 45], [90, 4 ] ] )
print(U < 45)

[[ True False]
 [False  True]]


In [183]:
X = np.array( [ [-2.5, 3.1, 7],
                [10, 11, 12] ] )
print("mean = ", X.mean())

mean =  6.766666666666667


In [186]:
import numpy as np
X_stat = np.array([[ 1, 2, 3], [ 4, -5, 6]])
print("mean = ", X_stat.mean())
print("Variance = ", X_stat.var())
print("Standard Deviation = ", X_stat.std())
print("min = ", X_stat.min())
print("max = ", X_stat.max())
print("sum = ", X_stat.sum())
print("product = ", X_stat.prod())

mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
min =  -5
max =  6
sum =  11
product =  -720


In [198]:
import numpy as np
Z = np.arange(18).reshape(2, 3, 3)
print(Z)
print(Z.sum(axis=2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[ 3 12 21]
 [30 39 48]]


In [204]:
  import numpy as np
N = np.arange(6).reshape(3,2)
print(N)
print("Transpose = ", N.T)

[[0 1]
 [2 3]
 [4 5]]
Transpose =  [[0 2 4]
 [1 3 5]]


In [11]:
import numpy as np
X_broad = np.ones((3,3))
print(X_broad)
Y_broad = np.arange(3)
print(Y_broad)
Z_broad = X_broad + Y_broad
print(Z_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
